import { NextRequest, NextResponse } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase'
import { getUser } from '@/lib/auth'

type StudyPurpose    = 'business_general' | 'business_engineer' | 'hobby_lifestyle' | 'hobby_reading'
type StudySubcategory = 'meeting' | 'review' | 'conference'
type StudyLevel      = 'beginner' | 'intermediate' | 'advanced'

// backward compat: old clients may still send these values
type LegacyPurpose = 'meeting' | 'review' | 'reading' | 'interview' | 'general'

const VALID_PURPOSES: (StudyPurpose | LegacyPurpose)[] = [
  'business_general', 'business_engineer', 'hobby_lifestyle', 'hobby_reading',
  'meeting', 'review', 'reading', 'interview', 'general',
]
const VALID_SUBCATEGORIES: StudySubcategory[] = ['meeting', 'review', 'conference']
const VALID_LEVELS: StudyLevel[] = ['beginner', 'intermediate', 'advanced']
const DOMAIN_MAX_LEN = 100

// ── 汎用フレーズ（全 purpose 共通 5選）──────────────────────────
const COMMON_PHRASES = [
  {
    phrase: 'heads-up',
    pronunciation: 'へっずあっぷ',
    meaning_ja: '事前の通知・予告。相手に前もって知らせること。',
    original_context: "Just a heads-up — the meeting has been moved to 3 PM.",
    difficulty: 1,
    usage_scene: 'business',
    engineer_level: 'junior',
  },
  {
    phrase: 'circle back',
    pronunciation: 'さーくるばっく',
    meaning_ja: '後で改めて話し合う・再度確認する。いったん後回しにして後で戻ること。',
    original_context: "Let's circle back on this after we get more data.",
    difficulty: 2,
    usage_scene: 'business',
    engineer_level: 'junior',
  },
  {
    phrase: 'on the same page',
    pronunciation: 'おん ざ せいむ ぺーじ',
    meaning_ja: '同じ認識・共通の理解を持っている状態。',
    original_context: "Before we start, let's make sure we're all on the same page.",
    difficulty: 1,
    usage_scene: 'business',
    engineer_level: 'junior',
  },
  {
    phrase: 'take ownership',
    pronunciation: 'ていく おーなーしっぷ',
    meaning_ja: 'タスクや問題に対して責任を持ち、主体的に最後まで取り組むこと。',
    original_context: "I'll take ownership of this issue and make sure it gets resolved by end of week.",
    difficulty: 2,
    usage_scene: 'business',
    engineer_level: 'mid',
  },
  {
    phrase: 'bandwidth',
    pronunciation: 'ばんどうぃず',
    meaning_ja: '時間的余裕・処理能力。「今その余裕がある？」という文脈で使われる。',
    original_context: "Do you have the bandwidth to take on another project this sprint?",
    difficulty: 2,
    usage_scene: 'business',
    engineer_level: 'mid',
  },
]

// ── シードキー別フレーズ（各 5選）────────────────────────────────
type SeedKey = StudyPurpose | StudySubcategory | LegacyPurpose
const PURPOSE_PHRASES: Record<SeedKey, typeof COMMON_PHRASES> = {

  // ── ビジネス：一般 ──────────────────────────────────────────
  business_general: [
    {
      phrase: 'bring to the table',
      pronunciation: 'ぶりんぐ とぅ ざ てーぶる',
      meaning_ja: '会議やチームに貢献できる強み・価値を提供する。',
      original_context: "What do you think she brings to the table that other candidates don't?",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'in the loop',
      pronunciation: 'いん ざ るーぷ',
      meaning_ja: '最新情報を共有・把握している状態。「keep me in the loop」でよく使われる。',
      original_context: "Please keep me in the loop on any updates from the client.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'at the end of the day',
      pronunciation: 'あっと じ えんど おぶ ざ でい',
      meaning_ja: '結局のところ・最終的に。重要なポイントをまとめる際に使う。',
      original_context: "At the end of the day, customer satisfaction is what matters most.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'going forward',
      pronunciation: 'ごーいんぐ ふぉーわーど',
      meaning_ja: '今後は・これからは。新しい方針や変更を宣言するときに使う。',
      original_context: "Going forward, all meeting notes will be shared on Notion.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'get on board',
      pronunciation: 'げっと おん ぼーど',
      meaning_ja: '賛同する・参加する。計画や新しいやり方を受け入れること。',
      original_context: "We need everyone to get on board with the new workflow before launch.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'ballpark figure',
      pronunciation: 'ぼーるぱーく ふぃぎゃー',
      meaning_ja: 'おおよその概算・大まかな見積もり。正確でなくてよいざっくりした数字。',
      original_context: "Can you give me a ballpark figure for how much this project will cost?",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'on the back burner',
      pronunciation: 'おん ざ ばっく ばーなー',
      meaning_ja: '優先度を下げて後回しにする。一旦保留にしておくこと。',
      original_context: "Let's put this feature on the back burner until we finish the launch.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'raise the bar',
      pronunciation: 'れいず ざ ばー',
      meaning_ja: '基準・水準を引き上げる。求められるレベルを高くすること。',
      original_context: "Their latest release really raised the bar for the whole industry.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'think outside the box',
      pronunciation: 'しんく あうとさいど ざ ぼっくす',
      meaning_ja: '既成の枠にとらわれず発想する。型破りなアイデアを出すこと。',
      original_context: "We need to think outside the box if we want to stand out from competitors.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'game changer',
      pronunciation: 'げーむ ちぇんじゃー',
      meaning_ja: '状況を一変させる画期的なもの・人。形勢を大きく変える存在。',
      original_context: "This new tool has been a real game changer for our productivity.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'ramp up',
      pronunciation: 'らんぷ あっぷ',
      meaning_ja: '増強する・段階的に強化する。生産や活動の規模を上げること。',
      original_context: "We need to ramp up hiring to keep pace with demand.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'get the ball rolling',
      pronunciation: 'げっと ざ ぼーる ろーりんぐ',
      meaning_ja: '物事を始動させる・着手する。プロジェクトなどを動き出させること。',
      original_context: "Let's get the ball rolling by scheduling a kickoff meeting this week.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'cut corners',
      pronunciation: 'かっと こーなーず',
      meaning_ja: '手を抜く・近道してコストや手間を省く。品質を犠牲にするニュアンス。',
      original_context: "We can't cut corners when it comes to security and testing.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'take it offline',
      pronunciation: 'ていく いっと おふらいん',
      meaning_ja: 'その議論は会議の場ではなく後で個別に行う、という意味。',
      original_context: "That's a great point, but let's take it offline and discuss after the meeting.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'win-win',
      pronunciation: 'うぃん うぃん',
      meaning_ja: '双方にとって利益がある状況。関係者全員が得をすること。',
      original_context: "This partnership is a win-win for both companies.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
  ],

  // ── ビジネス：エンジニア ＞ ミーティング・日常会話 ─────────────
  meeting: [
    {
      phrase: 'touch base',
      pronunciation: 'たっちべーす',
      meaning_ja: '簡単に連絡を取り合う・状況確認をする。',
      original_context: "Can we touch base tomorrow to sync on the project status?",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'table a discussion',
      pronunciation: 'てーぶる あ ぃすかっしょん',
      meaning_ja: '議題を一旦保留にする（米: 後回し、英: 提案する。米語の意味に注意）。',
      original_context: "Let's table this discussion and revisit it next week when we have more information.",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'action item',
      pronunciation: 'あくしょん あいてむ',
      meaning_ja: '会議後に誰かが担当する具体的なタスク・宿題。',
      original_context: "The action item from today's meeting is to prepare the demo by Friday.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'wrap up',
      pronunciation: 'らっぷあっぷ',
      meaning_ja: '締めくくる・終わりにする。会議や作業の終了を示す。',
      original_context: "We're running low on time — let's wrap up and send a summary.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'standing meeting',
      pronunciation: 'すたんでぃんぐ みーてぃんぐ',
      meaning_ja: '定期的に繰り返す会議（スタンドアップと区別して使われることも）。',
      original_context: "We have a standing meeting every Monday morning to align on priorities.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'sync up',
      pronunciation: 'しんく あっぷ',
      meaning_ja: '認識・状況を合わせる。短く情報共有して足並みをそろえること。',
      original_context: "Let's sync up after lunch on the API changes.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'parking lot',
      pronunciation: 'ぱーきんぐ ろっと',
      meaning_ja: '会議で本筋から外れた話題を一旦置いておく「保留リスト」。後で扱う論点置き場。',
      original_context: "Good question, but let's add it to the parking lot and come back to it later.",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'align on',
      pronunciation: 'あらいん おん',
      meaning_ja: '～について合意・認識を一致させる。方針をそろえること。',
      original_context: "Before we code, we need to align on the release date.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'loop in',
      pronunciation: 'るーぷ いん',
      meaning_ja: '関係者を会話・情報共有に巻き込む。「～にも共有しておく」。',
      original_context: "Let me loop in the design team before we finalize this.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'follow up',
      pronunciation: 'ふぉろー あっぷ',
      meaning_ja: '後追いで確認・連絡する。会議後のフォローや念押し。',
      original_context: "I'll follow up with an email summarizing today's decisions.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'quick sync',
      pronunciation: 'くいっく しんく',
      meaning_ja: '短時間の打ち合わせ。さっと認識合わせをするミーティング。',
      original_context: "Do you have five minutes for a quick sync on the bug?",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: "you're on mute",
      pronunciation: 'ゆあ おん みゅーと',
      meaning_ja: '（オンライン会議で）ミュートになっていて声が聞こえない、と伝える定番表現。',
      original_context: "Sorry, we can't hear you — I think you're on mute.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'drop off',
      pronunciation: 'どろっぷ おふ',
      meaning_ja: '通話・会議から抜ける。回線が切れて落ちる場合にも使う。',
      original_context: "I might drop off if my connection gets unstable.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'recap',
      pronunciation: 'りーきゃっぷ',
      meaning_ja: '要点を手短にまとめる・振り返る。会議の冒頭や締めで使う。',
      original_context: "Let me quickly recap what we agreed on before we wrap up.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'take the lead',
      pronunciation: 'ていく ざ りーど',
      meaning_ja: '主導する・旗振り役になる。ある業務の責任を持って進めること。',
      original_context: "Can you take the lead on organizing the kickoff?",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
  ],

  // ── ビジネス：エンジニア ＞ コードレビュー・技術ドキュメント ────
  review: [
    {
      phrase: 'pull request',
      pronunciation: 'ぷるりくえすと',
      meaning_ja: 'コードの変更内容をレビューしてもらうための申請。マージ前に他のエンジニアに確認を依頼する行為。',
      original_context: "Can you take a look at my pull request? I refactored the authentication module.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'LGTM',
      pronunciation: 'える じー てぃー えむ',
      meaning_ja: '"Looks Good To Me" の略。コードレビューで「問題なし・承認します」という意味で使う。',
      original_context: "I've reviewed all the changes. LGTM! Go ahead and merge whenever you're ready.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'nit',
      pronunciation: 'にっと',
      meaning_ja: '"nitpick" の略。些細な指摘。マージを妨げるほどではないが改善できる点。',
      original_context: "Nit: could you rename this variable to something more descriptive?",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'breaking change',
      pronunciation: 'ぶれいきんぐ ちぇんじ',
      meaning_ja: '後方互換性を壊す変更。既存のAPIやインターフェースが変わるため、利用側の修正が必要になる。',
      original_context: "This is a breaking change, so we need to bump the major version and update the migration guide.",
      difficulty: 3,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'under the hood',
      pronunciation: 'あんだー ざ ふっど',
      meaning_ja: '内部的に・裏側で。表面には見えないシステムの内部動作を指す。',
      original_context: "Under the hood, this library uses a binary search tree for efficient lookups.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'merge conflict',
      pronunciation: 'まーじ こんふりくと',
      meaning_ja: '複数の変更が衝突してそのままマージできない状態。手動で解消が必要。',
      original_context: "I got a merge conflict in the config file — can you help me resolve it?",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'edge case',
      pronunciation: 'えっじ けーす',
      meaning_ja: '端のケース・例外的な入力や条件。テストで見落としやすい境界の状況。',
      original_context: "Don't forget the edge case where the input list is empty.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'refactor',
      pronunciation: 'りふぁくたー',
      meaning_ja: '動作を変えずにコードの構造を整理・改善すること。',
      original_context: "This function is doing too much — let's refactor it into smaller pieces.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'tech debt',
      pronunciation: 'てっく でっと',
      meaning_ja: '技術的負債。短期的な妥協で後から返済（修正）が必要になるコード上の負担。',
      original_context: "We're accumulating tech debt by skipping tests to hit the deadline.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'blocker',
      pronunciation: 'ぶろっかー',
      meaning_ja: '作業の進行を止めている障害・依存先。解消しないと先に進めない要因。',
      original_context: "Is there any blocker preventing this PR from being merged?",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'boilerplate',
      pronunciation: 'ぼいらーぷれーと',
      meaning_ja: '毎回ほぼ同じ形で書く定型コード。本質的でない繰り返しの記述。',
      original_context: "This framework removes a lot of the boilerplate you'd otherwise write by hand.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'regression',
      pronunciation: 'りぐれっしょん',
      meaning_ja: '以前直したはずの不具合が再発すること・退行。新しい変更が既存機能を壊す現象。',
      original_context: "This change introduced a regression in the login flow — let's revert it.",
      difficulty: 3,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'ship it',
      pronunciation: 'しっぷ いっと',
      meaning_ja: 'リリースする・世に出す。「もう出して大丈夫」という承認のニュアンス。',
      original_context: "Tests are green and the review's done — let's ship it.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'happy path',
      pronunciation: 'はっぴー ぱす',
      meaning_ja: 'エラーや例外のない正常系の処理経路。まず動かすべき基本のフロー。',
      original_context: "Let's make sure the happy path works before we handle all the error cases.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'WIP',
      pronunciation: 'だぶりゅー あい ぴー',
      meaning_ja: '"Work In Progress" の略。作業途中でまだ完成していないことを示す。',
      original_context: "This PR is still WIP — please don't merge it yet.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
  ],

  // ── ビジネス：エンジニア ＞ 採用面接・プレゼン・カンファレンス ──
  conference: [
    {
      phrase: 'walk me through',
      pronunciation: 'うぉーく みー するー',
      meaning_ja: 'ステップごとに説明してもらう。面接や発表でプロセスを説明する際によく使われる。',
      original_context: "Could you walk me through your approach to solving this problem?",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'elaborate on',
      pronunciation: 'いらぼれいと おん',
      meaning_ja: '～について詳しく説明する。もう少し詳細を教えてほしいときに使う。',
      original_context: "Could you elaborate on your experience with distributed systems?",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'in terms of',
      pronunciation: 'いん たーむず おぶ',
      meaning_ja: '～の観点から・～に関しては。回答を構造的に説明するときに使う。',
      original_context: "In terms of scalability, our solution handles up to 10,000 concurrent users.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'room for improvement',
      pronunciation: 'るーむ ふぉー いんぷるーぶめんと',
      meaning_ja: '改善の余地がある・もっとよくなれる部分。弱みを謙虚に表現するときにも使える。',
      original_context: "There's always room for improvement in my public speaking skills.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'take a stab at',
      pronunciation: 'ていく あ すたぶ あっと',
      meaning_ja: '試しにやってみる。正解かどうかわからないが挑戦してみること。',
      original_context: "I'll take a stab at answering that, but feel free to correct me if I'm wrong.",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'deep dive',
      pronunciation: 'でぃーぷ だいぶ',
      meaning_ja: '深掘りして詳しく扱うこと。あるテーマを掘り下げて説明・検討する。',
      original_context: "Let's do a deep dive into the architecture in the next session.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'takeaway',
      pronunciation: 'ていくあうぇい',
      meaning_ja: '持ち帰るべき要点・学び。発表や会議で「ここだけは押さえてほしい点」。',
      original_context: "The key takeaway from this talk is that automation saves time in the long run.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'food for thought',
      pronunciation: 'ふーど ふぉー そーと',
      meaning_ja: '考える材料・一考に値する話。結論ではなく検討の種を提示するときに使う。',
      original_context: "I don't have an answer yet, but here's some food for thought.",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'set the stage',
      pronunciation: 'せっと ざ すてーじ',
      meaning_ja: '前提・背景を整えて本題に入りやすくする。話の土台づくり。',
      original_context: "Let me set the stage with some background before the demo.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'Q&A',
      pronunciation: 'きゅー あんど えー',
      meaning_ja: '質疑応答。発表の最後に質問を受け付ける時間。',
      original_context: "We'll have ten minutes for Q&A at the end of the presentation.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'break the ice',
      pronunciation: 'ぶれいく ざ あいす',
      meaning_ja: '場の緊張をほぐす・打ち解けるきっかけを作る。',
      original_context: "He told a quick joke to break the ice before starting his talk.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'on that note',
      pronunciation: 'おん ざっと のーと',
      meaning_ja: 'その流れで・それを踏まえて。話題を次へつなぐときの定番表現。',
      original_context: "On that note, let's move on to the next topic.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'live demo',
      pronunciation: 'らいぶ でも',
      meaning_ja: 'その場で実際に動かして見せる実演。スライドではなく本物を見せること。',
      original_context: "Let's switch to a live demo so you can see it working.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'shed light on',
      pronunciation: 'しぇっど らいと おん',
      meaning_ja: '～を明らかにする・解明する手がかりを与える。',
      original_context: "This data sheds light on why users drop off at the signup step.",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'in a nutshell',
      pronunciation: 'いん あ なっとしぇる',
      meaning_ja: '要するに・手短に言えば。要点を一言でまとめるときに使う。',
      original_context: "In a nutshell, our approach cuts latency in half.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
  ],

  // ── 趣味：旅行・ライフスタイル ──────────────────────────────
  hobby_lifestyle: [
    {
      phrase: 'off the beaten track',
      pronunciation: 'おふ ざ びーとん とらっく',
      meaning_ja: '人があまり訪れない穴場・王道ではない場所や体験。',
      original_context: "We wanted to go off the beaten track, so we skipped the touristy areas entirely.",
      difficulty: 3,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'bucket list',
      pronunciation: 'ばけっとりすと',
      meaning_ja: '死ぬまでにやりたいことリスト。「それはバケットリストにあった」のように使う。',
      original_context: "Visiting the Northern Lights has been on my bucket list for years.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'blend in',
      pronunciation: 'ぶれんど いん',
      meaning_ja: '周囲に溶け込む・目立たないようにする。現地の文化や人々に自然になじむこと。',
      original_context: "Dress like the locals if you want to blend in and avoid tourist traps.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'hidden gem',
      pronunciation: 'ひどん じぇむ',
      meaning_ja: 'あまり知られていないが素晴らしい場所・お店・体験。穴場。',
      original_context: "This little café is a hidden gem — locals only know about it.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'get a taste of',
      pronunciation: 'げっと あ てーすと おぶ',
      meaning_ja: '～を少し体験する・雰囲気を味わう。食文化に限らず幅広く使える。',
      original_context: "This tour lets you get a taste of local life without the typical tourist experience.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'wanderlust',
      pronunciation: 'わんだーらすと',
      meaning_ja: '旅への強い憧れ・放浪願望。知らない土地を見たくてたまらない気持ち。',
      original_context: "Her wanderlust took her to over thirty countries in five years.",
      difficulty: 3,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'soak up the atmosphere',
      pronunciation: 'そーく あっぷ ざ あともすふぃあ',
      meaning_ja: 'その場の雰囲気を存分に味わう・浸る。',
      original_context: "We just sat at a café to soak up the atmosphere of the old town.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'people-watching',
      pronunciation: 'ぴーぷる うぉっちんぐ',
      meaning_ja: '道行く人々を眺めて楽しむこと。カフェや広場での定番の過ごし方。',
      original_context: "I love people-watching from a sidewalk café with a coffee.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'splurge on',
      pronunciation: 'すぷらーじ おん',
      meaning_ja: '奮発して大枚をはたく・思い切ってお金を使う。',
      original_context: "We decided to splurge on a fancy dinner for our last night.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'recharge',
      pronunciation: 'りちゃーじ',
      meaning_ja: '英気を養う・充電する。休息して元気を取り戻すこと。',
      original_context: "I just need a quiet weekend to recharge before the next sprint.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'hit the road',
      pronunciation: 'ひっと ざ ろーど',
      meaning_ja: '出発する・出かける。「そろそろ行こう」というカジュアルな表現。',
      original_context: "It's getting late — we should hit the road before traffic gets bad.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'local delicacy',
      pronunciation: 'ろーかる でりかしー',
      meaning_ja: 'その土地ならではの名物料理・珍味。',
      original_context: "You have to try the local delicacy — it's only made in this region.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'must-see',
      pronunciation: 'ますと しー',
      meaning_ja: '必見の・絶対に見るべき。おすすめスポットを表すときに使う。',
      original_context: "The old castle is a must-see if you visit the city.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'unwind',
      pronunciation: 'あんわいんど',
      meaning_ja: '緊張をほぐしてくつろぐ・リラックスする。',
      original_context: "I like to unwind with a good book after a long day.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'go with the flow',
      pronunciation: 'ごー うぃず ざ ふろー',
      meaning_ja: '流れに身を任せる・成り行きに従う。計画にこだわらず柔軟に動くこと。',
      original_context: "We didn't plan much for the trip — we just went with the flow.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
  ],

  // ── 趣味：小説・読書 ────────────────────────────────────────
  hobby_reading: [
    {
      phrase: 'page-turner',
      pronunciation: 'ぺーじたーなー',
      meaning_ja: '読み始めると止まらない本・作品。「引きつけられて手が離せない」という意味。',
      original_context: "I couldn't put it down — it's a real page-turner from start to finish.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'plot twist',
      pronunciation: 'ぷろっと ついすと',
      meaning_ja: '物語の予想外の展開・どんでん返し。読者の予測を裏切る場面転換。',
      original_context: "The plot twist in the final chapter completely changed how I saw the whole story.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'read between the lines',
      pronunciation: 'りーど びとぅいーん ざ らいんず',
      meaning_ja: '行間を読む。明示されていない意図やメッセージを読み取ること。',
      original_context: "You have to read between the lines to understand what the author is really saying.",
      difficulty: 3,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'cliffhanger',
      pronunciation: 'くりふはんがー',
      meaning_ja: '結末が宙ぶらりんのまま終わる展開。次が気になってしまうような引き。',
      original_context: "The chapter ends on a cliffhanger — I had to start the next one immediately.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'in vivid detail',
      pronunciation: 'いん びびっど でぃてーる',
      meaning_ja: '生き生きとした描写で・ありありと。情景や感情が鮮明に伝わる表現。',
      original_context: "The author describes the setting in vivid detail, making you feel like you're really there.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'protagonist',
      pronunciation: 'ぷろたごにすと',
      meaning_ja: '物語の主人公・中心人物。',
      original_context: "The protagonist slowly realizes that his memories aren't his own.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'coming-of-age',
      pronunciation: 'かみんぐ おぶ えいじ',
      meaning_ja: '少年少女の成長・自立を描いた（物語）。「成長物語」のジャンルを指す。',
      original_context: "It's a classic coming-of-age story about a boy growing up in a small town.",
      difficulty: 3,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'unreliable narrator',
      pronunciation: 'あんりらいあぶる なれーたー',
      meaning_ja: '信頼できない語り手。読者をあえて誤解させる視点人物。',
      original_context: "The story uses an unreliable narrator, so you can't trust everything he says.",
      difficulty: 3,
      usage_scene: 'daily',
      engineer_level: 'mid',
    },
    {
      phrase: 'set in',
      pronunciation: 'せっと いん',
      meaning_ja: '（物語の）舞台が～に設定されている。時代や場所の設定を表す。',
      original_context: "The novel is set in 19th-century London.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'character development',
      pronunciation: 'きゃらくたー でぃべろっぷめんと',
      meaning_ja: '登場人物の心情や人格の変化・掘り下げ。物語を通じた成長描写。',
      original_context: "The character development in the second half makes the ending feel earned.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'slow burn',
      pronunciation: 'すろー ばーん',
      meaning_ja: 'じわじわと盛り上がっていく展開。最初は静かで後半に効いてくる作品。',
      original_context: "It's a slow burn, but the payoff in the final chapters is incredible.",
      difficulty: 3,
      usage_scene: 'daily',
      engineer_level: 'mid',
    },
    {
      phrase: 'tearjerker',
      pronunciation: 'てぃあじゃーかー',
      meaning_ja: '涙を誘う作品・お涙頂戴もの。感動して泣ける物語。',
      original_context: "Bring tissues — the last few chapters are a real tearjerker.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'spoiler',
      pronunciation: 'すぽいらー',
      meaning_ja: 'ネタバレ。結末や重要な展開を先に明かしてしまう情報。',
      original_context: "No spoilers, please — I haven't finished the book yet.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'gripping',
      pronunciation: 'ぐりっぴんぐ',
      meaning_ja: '手に汗握る・引き込まれるような。目が離せないほど魅力的な。',
      original_context: "The opening chapter is absolutely gripping.",
      difficulty: 2,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
    {
      phrase: 'relate to',
      pronunciation: 'りれいと とぅ',
      meaning_ja: '～に共感する・自分と重ね合わせる。',
      original_context: "I could really relate to the main character's struggles.",
      difficulty: 1,
      usage_scene: 'daily',
      engineer_level: 'junior',
    },
  ],

  // ── business_engineer: subcategory 未指定時のフォールバック ──
  business_engineer: [
    {
      phrase: 'touch base',
      pronunciation: 'たっちべーす',
      meaning_ja: '簡単に連絡を取り合う・状況確認をする。',
      original_context: "Can we touch base tomorrow to sync on the project status?",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'action item',
      pronunciation: 'あくしょん あいてむ',
      meaning_ja: '会議後に誰かが担当する具体的なタスク・宿題。',
      original_context: "The action item from today's meeting is to prepare the demo by Friday.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'LGTM',
      pronunciation: 'える じー てぃー えむ',
      meaning_ja: '"Looks Good To Me" の略。コードレビューで「問題なし・承認します」という意味で使う。',
      original_context: "I've reviewed all the changes. LGTM! Go ahead and merge whenever you're ready.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'breaking change',
      pronunciation: 'ぶれいきんぐ ちぇんじ',
      meaning_ja: '後方互換性を壊す変更。既存のAPIやインターフェースが変わるため、利用側の修正が必要になる。',
      original_context: "This is a breaking change, so we need to bump the major version and update the migration guide.",
      difficulty: 3,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'walk me through',
      pronunciation: 'うぉーく みー するー',
      meaning_ja: 'ステップごとに説明してもらう。面接や発表でプロセスを説明する際によく使われる。',
      original_context: "Could you walk me through your approach to solving this problem?",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'sync up',
      pronunciation: 'しんく あっぷ',
      meaning_ja: '認識・状況を合わせる。短く情報共有して足並みをそろえること。',
      original_context: "Let's sync up after lunch on the API changes.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'blocker',
      pronunciation: 'ぶろっかー',
      meaning_ja: '作業の進行を止めている障害・依存先。解消しないと先に進めない要因。',
      original_context: "Is there any blocker preventing this PR from being merged?",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'tech debt',
      pronunciation: 'てっく でっと',
      meaning_ja: '技術的負債。短期的な妥協で後から修正が必要になるコード上の負担。',
      original_context: "We're accumulating tech debt by skipping tests to hit the deadline.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'ramp up',
      pronunciation: 'らんぷ あっぷ',
      meaning_ja: '増強する・段階的に強化する。体制や生産の規模を上げること。',
      original_context: "We need to ramp up the team to deliver this on time.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'ship it',
      pronunciation: 'しっぷ いっと',
      meaning_ja: 'リリースする・世に出す。「もう出して大丈夫」という承認のニュアンス。',
      original_context: "Tests are green and the review's done — let's ship it.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'align on',
      pronunciation: 'あらいん おん',
      meaning_ja: '～について合意・認識を一致させる。方針をそろえること。',
      original_context: "Let's align on the scope before we start coding.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'edge case',
      pronunciation: 'えっじ けーす',
      meaning_ja: '端のケース・例外的な入力や条件。テストで見落としやすい境界の状況。',
      original_context: "Don't forget the edge case where the input list is empty.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'follow up',
      pronunciation: 'ふぉろー あっぷ',
      meaning_ja: '後追いで確認・連絡する。会議後のフォローや念押し。',
      original_context: "I'll follow up with an email summarizing the action items.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'deep dive',
      pronunciation: 'でぃーぷ だいぶ',
      meaning_ja: '深掘りして詳しく扱うこと。あるテーマを掘り下げて検討する。',
      original_context: "Let's do a deep dive into the performance issue tomorrow.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'wrap up',
      pronunciation: 'らっぷあっぷ',
      meaning_ja: '締めくくる・終わりにする。作業や会議の終了を示す。',
      original_context: "Let's wrap up here and send out a summary.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
  ],

  // ── 後方互換：旧 purpose 値 ─────────────────────────────────
  general: [
    {
      phrase: 'leverage',
      pronunciation: 'れぼりっじ',
      meaning_ja: '活用する・うまく利用する（動詞）。強みや既存リソースを最大限に使うこと。',
      original_context: "We should leverage our existing infrastructure rather than building from scratch.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'low-hanging fruit',
      pronunciation: 'ろーはんぎんぐ ふるーと',
      meaning_ja: '簡単に達成できる目標・すぐに手に入る成果。労力の少ない改善点。',
      original_context: "Let's start with the low-hanging fruit and tackle the easier wins first.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'move the needle',
      pronunciation: 'むーぶ ざ にーどる',
      meaning_ja: '状況を改善する・成果を出す。指標や状況を変化させるインパクトを与えること。',
      original_context: "We need initiatives that actually move the needle on user retention.",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'bottleneck',
      pronunciation: 'ぼとるねっく',
      meaning_ja: 'システムやプロセス全体の速度を制限している箇所。パフォーマンス問題の原因。',
      original_context: "The database query is the bottleneck. We need to add an index to speed things up.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'workaround',
      pronunciation: 'わーくあらうんど',
      meaning_ja: '問題の根本解決ではなく、一時的に回避するための手段。暫定対応・応急処置。',
      original_context: "This is just a workaround for now. We'll fix the root cause properly in the next sprint.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'game changer',
      pronunciation: 'げーむ ちぇんじゃー',
      meaning_ja: '状況を一変させる画期的なもの・人。形勢を大きく変える存在。',
      original_context: "This new tool has been a real game changer for our team.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'think outside the box',
      pronunciation: 'しんく あうとさいど ざ ぼっくす',
      meaning_ja: '既成の枠にとらわれず発想する。型破りなアイデアを出すこと。',
      original_context: "We need to think outside the box to solve this.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'raise the bar',
      pronunciation: 'れいず ざ ばー',
      meaning_ja: '基準・水準を引き上げる。求められるレベルを高くすること。',
      original_context: "Their work really raised the bar for the rest of us.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'get the ball rolling',
      pronunciation: 'げっと ざ ぼーる ろーりんぐ',
      meaning_ja: '物事を始動させる・着手する。',
      original_context: "Let's get the ball rolling with a quick kickoff.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'ballpark figure',
      pronunciation: 'ぼーるぱーく ふぃぎゃー',
      meaning_ja: 'おおよその概算・大まかな見積もり。',
      original_context: "Can you give me a ballpark figure for the timeline?",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'tech debt',
      pronunciation: 'てっく でっと',
      meaning_ja: '技術的負債。短期的な妥協で後から修正が必要になるコード上の負担。',
      original_context: "We should pay down some tech debt this sprint.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'edge case',
      pronunciation: 'えっじ けーす',
      meaning_ja: '端のケース・例外的な入力や条件。見落としやすい境界の状況。',
      original_context: "We need a test for the edge case where the value is zero.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'refactor',
      pronunciation: 'りふぁくたー',
      meaning_ja: '動作を変えずにコードの構造を整理・改善すること。',
      original_context: "Let's refactor this before adding more features.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'deep dive',
      pronunciation: 'でぃーぷ だいぶ',
      meaning_ja: '深掘りして詳しく扱うこと。',
      original_context: "Let's schedule a deep dive into the metrics next week.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'takeaway',
      pronunciation: 'ていくあうぇい',
      meaning_ja: '持ち帰るべき要点・学び。',
      original_context: "The main takeaway is that we shipped faster by automating tests.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
  ],
  reading: [
    {
      phrase: 'deprecated',
      pronunciation: 'でぷれけいてぃど',
      meaning_ja: '非推奨・廃止予定。将来的に削除される機能や構文を示す。',
      original_context: "This API endpoint is deprecated and will be removed in v3.0. Please use the new endpoint instead.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'prerequisite',
      pronunciation: 'ぷりれくぃじっと',
      meaning_ja: '前提条件・事前に必要なもの。インストールや設定が必要な依存関係など。',
      original_context: "Before proceeding, make sure you've installed all prerequisites listed in the README.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'under the hood',
      pronunciation: 'あんだー ざ ふっど',
      meaning_ja: '内部的に・裏側で。表面には見えないシステムの内部動作を指す。',
      original_context: "Under the hood, this library uses a binary search tree for efficient lookups.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'at a high level',
      pronunciation: 'あっと あ はい れべる',
      meaning_ja: '概要として・大まかに見て。細部ではなく全体像の説明。',
      original_context: "At a high level, the architecture consists of three layers: presentation, business logic, and data.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'out of scope',
      pronunciation: 'あうと おぶ すこーぷ',
      meaning_ja: '今回の対応範囲外であること。現在のタスクやスプリントに含まれない機能・修正を指す。',
      original_context: "That feature request is out of scope for this sprint. Let's add it to the backlog.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'backward compatible',
      pronunciation: 'ばっくわーど こんぱてぃぶる',
      meaning_ja: '後方互換性がある。古いバージョンや既存の利用側を壊さないこと。',
      original_context: "This change is backward compatible, so existing clients won't break.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'as follows',
      pronunciation: 'あず ふぉろーず',
      meaning_ja: '以下の通り。手順や項目を列挙する前に使う定型表現。',
      original_context: "The setup steps are as follows.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'refer to',
      pronunciation: 'りふぁー とぅ',
      meaning_ja: '～を参照する・参考にする。ドキュメントで案内するときの定番。',
      original_context: "Refer to the README for the full configuration options.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'note that',
      pronunciation: 'のーと ざっと',
      meaning_ja: '～に注意。重要な前提や注意点を示すときの言い回し。',
      original_context: "Note that this command requires admin privileges.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'by default',
      pronunciation: 'ばい でぃふぉると',
      meaning_ja: 'デフォルトでは・初期設定では。特に指定しない場合の挙動。',
      original_context: "By default, the cache expires after one hour.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'snippet',
      pronunciation: 'すにぺっと',
      meaning_ja: '短いコード片・抜粋。例示用の小さなコードのかたまり。',
      original_context: "Here's a snippet showing how to call the API.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'placeholder',
      pronunciation: 'ぷれーすほるだー',
      meaning_ja: '仮の値・差し替え前提の入力例。実際の値に置き換えて使う。',
      original_context: "Replace the placeholder with your actual API key.",
      difficulty: 2,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'caveat',
      pronunciation: 'きゃべあっと',
      meaning_ja: '注意点・但し書き。「ただし～」という条件や警告。',
      original_context: "One caveat: this only works on Linux, not on Windows.",
      difficulty: 3,
      usage_scene: 'technical',
      engineer_level: 'mid',
    },
    {
      phrase: 'as needed',
      pronunciation: 'あず にーでぃっど',
      meaning_ja: '必要に応じて。状況に合わせて任意で行うこと。',
      original_context: "Adjust the timeout value as needed for your environment.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
    {
      phrase: 'for instance',
      pronunciation: 'ふぉー いんすたんす',
      meaning_ja: '例えば。具体例を挙げるときの表現（for example とほぼ同義）。',
      original_context: "You can use any logger — for instance, Winston or Pino.",
      difficulty: 1,
      usage_scene: 'technical',
      engineer_level: 'junior',
    },
  ],
  interview: [
    {
      phrase: 'walk me through',
      pronunciation: 'うぉーく みー するー',
      meaning_ja: 'ステップごとに説明してもらう。面接で経験やプロセスを説明する際によく使われる。',
      original_context: "Could you walk me through your approach to solving this problem?",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'elaborate on',
      pronunciation: 'いらぼれいと おん',
      meaning_ja: '～について詳しく説明する。もう少し詳細を教えてほしいときに使う。',
      original_context: "Could you elaborate on your experience with distributed systems?",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
    {
      phrase: 'in terms of',
      pronunciation: 'いん たーむず おぶ',
      meaning_ja: '～の観点から・～に関しては。回答を構造的に説明するときに使う。',
      original_context: "In terms of scalability, our solution handles up to 10,000 concurrent users.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'greatest strength',
      pronunciation: 'ぐれいてすと すとれんぐす',
      meaning_ja: '最大の強み。「What\'s your greatest strength?」は面接の定番質問。',
      original_context: "My greatest strength is my ability to break down complex problems into manageable steps.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'room for improvement',
      pronunciation: 'るーむ ふぉー いんぷるーぶめんと',
      meaning_ja: '改善の余地がある・もっとよくなれる部分。弱みを謙虚に表現するときにも使える。',
      original_context: "There's always room for improvement in my public speaking skills.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'tell me about yourself',
      pronunciation: 'てる みー あばうと ゆあせるふ',
      meaning_ja: '「自己紹介してください」。面接の最初の定番質問。',
      original_context: "So, to start — tell me about yourself and your background.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'team player',
      pronunciation: 'ちーむ ぷれいやー',
      meaning_ja: 'チームで協調して働ける人。協調性のある人材を表す表現。',
      original_context: "I consider myself a team player who values open communication.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'take initiative',
      pronunciation: 'ていく いにしあてぃぶ',
      meaning_ja: '主体的に動く・率先して取り組む。指示を待たず自ら行動すること。',
      original_context: "I took the initiative to automate the deployment process.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'under pressure',
      pronunciation: 'あんだー ぷれっしゃー',
      meaning_ja: 'プレッシャーの下で。「I work well under pressure」で粘り強さを示す定番。',
      original_context: "I tend to stay calm and focused under pressure.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'career goal',
      pronunciation: 'きゃりあ ごーる',
      meaning_ja: 'キャリア上の目標。「将来どうなりたいか」を語るときに使う。',
      original_context: "My long-term career goal is to grow into a technical lead role.",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'fit for the role',
      pronunciation: 'ふぃっと ふぉー ざ ろーる',
      meaning_ja: 'その職務に合っている・適任である。',
      original_context: "I believe my background makes me a good fit for the role.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'hands-on experience',
      pronunciation: 'はんずおん えくすぺりえんす',
      meaning_ja: '実務での実体験・手を動かした経験。座学ではなく実践経験。',
      original_context: "I have hands-on experience building and scaling REST APIs.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'attention to detail',
      pronunciation: 'あてんしょん とぅ でぃてーる',
      meaning_ja: '細部への注意・几帳面さ。見落としなく丁寧に仕事をする資質。',
      original_context: "This role requires strong attention to detail when reviewing code.",
      difficulty: 2,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'why should we hire you',
      pronunciation: 'わい しゅっど うぃー はいあ ゆー',
      meaning_ja: '「なぜあなたを採用すべきか」。強みを売り込む面接の定番質問。',
      original_context: "Why should we hire you over the other candidates?",
      difficulty: 1,
      usage_scene: 'business',
      engineer_level: 'junior',
    },
    {
      phrase: 'step out of my comfort zone',
      pronunciation: 'すてっぷ あうと おぶ まい かんふぉーと ぞーん',
      meaning_ja: '自分の慣れた領域を出て挑戦する。成長のために負荷をかけること。',
      original_context: "I took this project to step out of my comfort zone and learn something new.",
      difficulty: 3,
      usage_scene: 'business',
      engineer_level: 'mid',
    },
  ],
}

export async function POST(req: NextRequest) {
  const user = await getUser()
  if (!user) return NextResponse.json({ error: 'ログインが必要です' }, { status: 401 })

  let body: {
    study_purpose: StudyPurpose | LegacyPurpose
    study_subcategory?: StudySubcategory
    study_level: StudyLevel
    study_domain?: string
  }
  try { body = await req.json() }
  catch { return NextResponse.json({ error: 'リクエストの解析に失敗しました' }, { status: 400 }) }

  if (!VALID_PURPOSES.includes(body.study_purpose))
    return NextResponse.json({ error: '学習目的が不正です' }, { status: 400 })
  if (body.study_subcategory && !VALID_SUBCATEGORIES.includes(body.study_subcategory))
    return NextResponse.json({ error: 'サブカテゴリが不正です' }, { status: 400 })
  if (!VALID_LEVELS.includes(body.study_level))
    return NextResponse.json({ error: 'レベルが不正です' }, { status: 400 })

  const rawDomain = (body.study_domain ?? '').trim()
  const study_domain = rawDomain.slice(0, DOMAIN_MAX_LEN) || undefined

  const db = getSupabaseAdmin()

  // 1. ユーザーメタデータに学習設定を保存
  const metaUpdate: Record<string, unknown> = {
    ...user.user_metadata,
    study_purpose: body.study_purpose,
    study_level: body.study_level,
    study_domain,
    onboarding_complete: true,
  }
  if (body.study_subcategory) {
    metaUpdate.study_subcategory = body.study_subcategory
  } else {
    // subcategoryが空の場合は削除（purpose変更時のクリーンアップ）
    delete metaUpdate.study_subcategory
  }

  const { error: metaError } = await db.auth.admin.updateUserById(user.id, {
    user_metadata: metaUpdate,
  })
  if (metaError) {
    return NextResponse.json({ error: 'ユーザー設定の保存に失敗しました' }, { status: 500 })
  }

  // 2. フレーズが0件の場合のみシードフレーズを挿入
  const { count } = await db
    .from('phrases')
    .select('id', { count: 'exact', head: true })
    .eq('user_id', user.id)
    .is('deleted_at', null)

  if ((count ?? 0) === 0) {
    // subcategory が指定されていればそれを優先、なければ purpose で引く
    const seedKey: SeedKey = body.study_subcategory ?? body.study_purpose
    const purposePhrases = PURPOSE_PHRASES[seedKey] ?? PURPOSE_PHRASES['business_general']
    const today = new Date().toISOString().split('T')[0]
    const rows = [...COMMON_PHRASES, ...purposePhrases].map((p) => ({
      ...p,
      user_id: user.id,
      added_date: today,
      source_type: 'System',
      source_title: '初期フレーズ',
    }))
    const { error: insertError } = await db.from('phrases').insert(rows)
    if (insertError) {
      console.error('[onboarding] seed insert error:', insertError.message)
    }
  }

  return NextResponse.json({ success: true })
}
